FROM node:16-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm install --verbose

COPY . .

RUN npm run build # Assuming you have a build script

FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/dist . # Assuming build output is in dist folder

EXPOSE 3000

ENTRYPOINT ["node", "./dist/index.js"]